// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkYbd_GbQOgQiEZGI47DHeseNkkbHBQOQ',
    appId: '1:107036849789:web:1421e511b6fdf1c33a2314',
    messagingSenderId: '107036849789',
    projectId: 'lodge-b027a',
    authDomain: 'lodge-b027a.firebaseapp.com',
    storageBucket: 'lodge-b027a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIjA_MqF2Vo72ddkzEdvmpMH1CNZuwT3g',
    appId: '1:107036849789:android:b3ff491828fae1c03a2314',
    messagingSenderId: '107036849789',
    projectId: 'lodge-b027a',
    storageBucket: 'lodge-b027a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYuoyefBPuYsv9_o6fQCVN65yNtDKqArQ',
    appId: '1:107036849789:ios:38ac67a545838b573a2314',
    messagingSenderId: '107036849789',
    projectId: 'lodge-b027a',
    storageBucket: 'lodge-b027a.appspot.com',
    iosClientId: '107036849789-vjt26mhh44f2gi7ehoedj38eh2cg72hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.lodgeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYuoyefBPuYsv9_o6fQCVN65yNtDKqArQ',
    appId: '1:107036849789:ios:38ac67a545838b573a2314',
    messagingSenderId: '107036849789',
    projectId: 'lodge-b027a',
    storageBucket: 'lodge-b027a.appspot.com',
    iosClientId: '107036849789-vjt26mhh44f2gi7ehoedj38eh2cg72hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.lodgeApp',
  );
}
